### PR TITLE
Add option to skip css file creation

### PR DESCRIPTION
**Pull request by petetnt**
Hey, cool app!

This PR adds option `skip` to `cssExtension` question, as sometimes stylesheet files aren't needed (for example for CSS-in-JS.

Feel free to add improvements or suggestions!

Signed-off-by: Pete Nykanen <pete.a.nykanen@gmail.com>

### CODE REVIEW

**Comment by CVarisco** [comment]
Hi @petetnt ,
Good idea, I'll merge today your work 👍 

Thanks a lot for your support.

**Comment by bsonntag** [comment]
What if someone wants to use `.skip` as an extension? (Who knows if someone will come up with a CSS extension language called Skip?)

What about doing this with a flag instead?
For example: `create-component-app --no-css`

Or maybe an extra question, like `Do you want to create a style file? [Y/n]`.

**Comment by petetnt** [comment]
@bsonntag Yeah, I thought about that. First I was going with `none`, but "what if someone wants to use no extension for some reason". 

An additional question would be better, but would have created a bit more complexity too at this point. I would be okay with a flag too.

**Comment by bsonntag** [comment]
I was also going to suggest checking for empty input, but like you said: "what if someone wants to use no extension for some reason".

**Comment by CVarisco** [comment]
Thanks for your support @petetnt @bsonntag  
I think that the best solution is manage the workflow with the question:
"Do you want to create a style file? [Y/n]"

Because with this implementation we can change the type of question of css extension from "list" to "input".
In this way the user can do what he want 🙂 

What do you think about it ?

**Comment by petetnt** [comment]
Sounds good to me, I can implement that tonight 👍

**Comment by CVarisco** [comment]
@petetnt cool!
I'm working on the custom template feature, if you need some help I'm here 🙂

**Comment by CVarisco** [comment]
Hey @petetnt,

I'm adding the new feature   
https://github.com/CVarisco/create-component-app/pull/6

I will merge it in the next hour!

**Comment by petetnt** [comment]
I was bit busy tonight, but I'll rebase this to the master and work on the additions over the weekend 👍

**Comment by CVarisco** [comment]
Don't worry @petetnt contribute need to be a pleasure not a duty 🙂

Thanks again for your support 💪🏻

**Comment by CVarisco** [comment]
Hi @petetnt !

@labithiotis send a PR with a interesting improvement.
I think that this PR can be useful to the other.
So, I'm developing the "skip" feature and  merge this feature to the other 🙂

**Comment by petetnt** [comment]
Cool! ❤️  Sorry that I didn't get back to you on weekend there, was pretty caught up to my summer vacation 🌴

**Comment by CVarisco** [comment]
@petetnt don't worry 🙂  
I'm really happy to have someone that contribute 👍 

Thanks again for your support!

**Pull request merged**
